import 'package:dio/dio.dart';

class ApiClient {
  final baseUrl = 'https://api.clashofclans.com/';

  final apiKey =
      "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImU5NWQ3YmNmLTc4MjEtNDNhOC04NzY5LTk5ZDQxMWZkYzk0MyIsImlhdCI6MTY3NDIwODAwOCwic3ViIjoiZGV2ZWxvcGVyLzcxYzU0YjEwLWZiOTAtYzcyNy00MzJhLTgxNDVlMWU4NjMyMCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjExNy4yMzkuMjUxLjU4Il0sInR5cGUiOiJjbGllbnQifV19.AhppCuOgt9G0-dzaOQZaC1xWdePMHSFYMKmj3ufS2m9UEieZaZ8guWO2_W6mr0O_fla98cGZE0HOLRYUIEb5JQ";
  var dio = Dio();
}
